version: '3.9'
services:

  root-service:
    image: ssamoilenko/hsal2-root-service:latest
    build:
      context: ./services
      dockerfile: docker/fat.Dockerfile
      args:
        MODULE_NAME: root-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/roots
      - APP_XOR_SERVICE_URL=http://xor-service:8082
      # CPS of a 'slow' operation compared to a cache lookup
      - APP_CALCULATION_CPS_LIMIT=100
      # How fast the cache will be filled
      - APP_MAX_RANDOM_VALUE=100000
      - MANAGEMENT_STATSD_METRICS_EXPORT_HOST=telegraf
      - LOGGING_LEVEL_COM_EXAMPLE_ROOTSERVICE=INFO
    ports:
      - '8081:8081'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      mongodb:
        condition: service_healthy

  xor-service:
    image: ssamoilenko/hsal2-xor-service:latest
    build:
      context: ./services
      dockerfile: docker/fat.Dockerfile
      args:
        MODULE_NAME: xor-service
    environment:
      - APP_ELASTICSEARCH_URL=elasticsearch:9200
      # CPS of a 'slow' operation compared to a cache lookup
      - APP_CALCULATION_CPS_LIMIT=500
      # Number of ahead calculations to be cached
      - APP_CALCULATION_CACHE_SIZE=20
      - MANAGEMENT_STATSD_METRICS_EXPORT_HOST=telegraf
      - LOGGING_LEVEL_COM_EXAMPLE_XORSERVICE=INFO
    ports:
      - '8082:8082'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx:/var/log/nginx
    ports:
      - '8080:8080'
    depends_on:
      root-service:
        condition: service_healthy
      xor-service:
        condition: service_healthy

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    restart: always
    volumes:
      - ./data/mongodb:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    volumes:
      - ./data/elasticsearch:/bitnami/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx1024m -Xms256m
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 5s
      timeout: 5s
      retries: 20

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:2375:2375'
    environment:
      - LOG_LEVEL=warning # debug,info,notice,warning,err,crit,alert,emerg
      - CONTAINERS=1
      - INFO=1

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    restart: always
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8125:8125/udp'
    depends_on:
      socket-proxy:
        condition: service_started
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=qwerty123qwerty123
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=qwerty123qwerty123
    ports:
      - '8086:8086'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8086/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana-oss
    container_name: grafana-server
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel
    ports:
      - '3000:3000'
    depends_on:
      influxdb:
        condition: service_healthy

  siege:
    image: jstarcher/siege
    container_name: siege
    profiles:
      - siege
    depends_on:
      - nginx
    command: -c 10 -t 30m http://nginx:8080/root/xor/random
