###
GET http://localhost:8082/weather/city/Sydney

###
GET http://localhost:8081/actuator/metrics

###
GET http://localhost:8081/root/xor/random

###
GET http://localhost:9200/_cat/indices?v

// Drop ES index:
###
DELETE http://localhost:9200/xor-cache

###
// Get ES Index:
GET http://localhost:9200/xor-cache/_search

###
// Get ES Index mapping
GET http://localhost:9200/xor-cache/_mapping
