spring:
  application.name: geo-service

server.port: 8081

app:
  weather-api:
    url: http://api.weatherapi.com/v1
    # Dumb protection against dumb crawlers
    obfuscated-key: ICAgICAgICAgIDQwMzVkOGRmZTEyMTQ5NGRiYmIyMjM4NTUyMzE2MDIgICAgICAgICAgICAgCg==
  weather-service:
    url: http://localhost:8082

management:
  endpoints.web.exposure.include: metrics
  statsd:
    metrics:
      export:
        enabled: true
        flavor: telegraf
        port: 8125
        step: 10s
logging:
  level:
    org.elasticsearch.client.RestClient: ERROR
    com.example.geoservice: DEBUG
